on:
  push:
    branches:
      - main
    paths:
      - "template/cv.typ"
      - "lib.typ"
      - ".github/workflows/cv.yml"
  pull_request:
  workflow_dispatch:

jobs:
  format-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Format with typstyle
        uses: grayespinoza/typstyle-action@main

      - name: Commit formatted files
        uses: stefanzweifel/git-auto-commit-action@master
        with:
          commit_message: "chore: Formatted using typstyle"

      - name: Setup Fontist
        uses: fontist/setup-fontist@v2

      - name: Install fonts
        run: |
          fontist install 'Noto Sans'
          fontist install 'Fira Sans'
          fontist install 'Roboto'
          mkdir -p ~/.local/share/fonts
          mv ~/.fontist/fonts/* ~/.local/share/fonts

      - name: Setup Font Awesome
        run: |
          export FA_VERSION=6.7.2
          wget https://github.com/FortAwesome/Font-Awesome/releases/download/${FA_VERSION}/fontawesome-free-${FA_VERSION}-desktop.zip
          unzip fontawesome-free-${FA_VERSION}-desktop.zip
          mv fontawesome-free-${FA_VERSION}-desktop/otfs/*.otf ~/.local/share/fonts

      - name: Setup Just
        uses: extractions/setup-just@v3

      - name: Setup Typst
        uses: typst-community/setup-typst@v4

      - name: Use local package
        run: |
          sed -i 's|#import "@preview/neat-cv:[0-9.]\+"|#import "../lib.typ"|' template/cv.typ | head

      - name: Compile CV
        run: just

      - name: Upload CV artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv
          path: template/cv.pdf
          retention-days: 7
